Repository milieuinfo/webcomponent-vl-ui-functional-header, pull requests merged in 2020-04, with the labels that each got.

#1 Initiële code
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task.md
  .github/release-drafter.yml
  .gitignore
  .mocharc.js
  .npmignore
  CODEOWNERS
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/vl-functional-header.html
  dist/index.js
  dist/style.css
  dist/style.css.map
  dist/style.scss
  dist/vl-functional-header.js
  dist/vl-functional-header.min.js
  dist/vl-functional-header.src.js
  docker-compose-release.yml
  index.js
  package-lock.json
  package.json
  renovate.json
  src/index.js
  src/style.css
  src/style.css.map
  src/style.scss
  src/vl-functional-header.js
  test/docker-compose.yml
  test/e2e/components/vl-functional-header.js
  test/e2e/functional-header.test.js
  test/e2e/pages/vl-functional-header.page.js
  test/unit/vl-functional-header.test.html
  wct.docker.conf.json
  wct.local.conf.json
Labels: chore

#2 Update dependency @govflanders/vl-ui-button to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#3 Update dependency @govflanders/vl-ui-input-field to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#4 Update dependency @govflanders/vl-ui-link to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#6 Update dependency @govflanders/vl-ui-util to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#5 Introductie acties functionaliteit
  demo/vl-functional-header.html
  dist/vl-functional-header.js
  dist/vl-functional-header.min.js
  dist/vl-functional-header.src.js
  src/vl-functional-header.js
  test/e2e/components/vl-functional-header.js
  test/e2e/functional-header.test.js
  test/e2e/pages/vl-functional-header.page.js
  test/unit/vl-functional-header.test.html
Labels: enhancement
