Repository milieuinfo/webcomponent-vl-ui-functional-header, pull requests merged in 2020-06, with the labels that each got.

#12 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  CODEOWNERS
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/vl-functional-header.html
  index.js
  package-lock.json
  package.json
  src/index.js
  src/style.css
  src/style.css.map
  src/vl-functional-header.js
  test/e2e/components/vl-functional-header.js
  test/e2e/functional-header.test.js
  test/e2e/pages/vl-functional-header.page.js
  test/unit/vl-functional-header.test.html
Labels: chore

#13 Import sinon uit node_modules voor de unit testen
  package-lock.json
  src/style.css
  src/style.css.map
  test/unit/vl-functional-header.test.html
Labels: bugfix

#17 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
Labels: bug

#19 Deduplicatie NPM run scripts Update naar latest vl-ui-util en vl-ui-core
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore
